import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.scss']
})
export class AppComponent {
  title = 'project';
states : any = [
  "Rajasthan",
  "Madhya Pradesh",
  "West Bengal",
  "Karnataka",
  "Kerala",
  "Assam",
  "Arunachal Pradesh",
]
  cities : any = [
    "Ajmer",
    "Alwar",
    "Beawar",
    "Bikaner",
    "Bharatpur",
    "Bhilwara",
    "Chittaurgarh",
    "Jaipur",
    "Jaisalmer",
    "Jodhpur",
    "Kumbhalgarh",
    "Ladnu",
    "Lakheri",
    "Lalsot",
    "Losal",
    "Laxmangarh",
    "Makrana",
    "Malpura",
    "Mandalgarh",
    "Mandawa",
    "Mangrol",
    "Merta City",
    "Mount Abu",
    "Nadbai",
    "Nagar",
    "Nagaur",
    "Nasirabad",
    "Nathdwara",
    "Neem-Ka-Thana",
    "Nimbahera",
    "Nohar",
    "Nokha",
    "Pali",
    "Phalodi",
    "Phulera",
    "Pilani",
    "Pilibanga",
    "Pindwara",
    "Pipar City",
    "Prantij",
    "Pratapgarh",
    "Raisinghnagar",
    "Rajakhera",
    "Rajaldesar",
    "Rajgarh (Alwar)",
    "Rajgarh (Churu)",
    "Rajsamand",
    "Ramganj Mandi",
    "Ramngarh",
    "Ratangarh",
    "Rawatbhata",
    "Rawatsar",
    "Reengus",
    "Sadri",
    "Sadulshahar",
    "Sadulpur",
    "Sagwara",
    "Sambhar",
    "Sanchore",
    "Sangaria",
    "Sardarshahar",
    "Sawai Madhopur",
    "Shahpura",
    "Shahpura",
    "Sheoganj",
    "Sikar",
    "Sirohi",
    "Sojat",
    "Sri Madhopur",
    "Sujangarh",
    "Sumerpur",
    "Suratgarh",
    "Taranagar",
    "Todabhim",
    "Todaraisingh",
    "Tonk",
    "Udaipur",
    "Udaipurwati",
    "Vijainagar, Ajmer"
    ];




}
